/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CreateListingInput = IDL.Record({
  'id' : IDL.Text,
  'region' : IDL.Text,
  'model' : IDL.Text,
  'mileage' : IDL.Nat,
  'source' : IDL.Text,
  'make' : IDL.Text,
  'trim' : IDL.Text,
  'year' : IDL.Nat,
  'listingUrl' : IDL.Text,
  'dealerName' : IDL.Text,
  'price' : IDL.Nat,
  'condition' : IDL.Text,
  'images' : IDL.Vec(ExternalBlob),
});
export const AlertFormulaMatch = IDL.Record({
  'formulaName' : IDL.Text,
  'matchedListingIds' : IDL.Vec(IDL.Text),
  'formulaId' : IDL.Text,
});
export const Time = IDL.Int;
export const PrivateNote = IDL.Record({
  'id' : IDL.Text,
  'text' : IDL.Text,
  'lastUpdated' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CrossModelResult = IDL.Record({
  'id' : IDL.Text,
  'region' : IDL.Text,
  'model' : IDL.Text,
  'mileage' : IDL.Nat,
  'source' : IDL.Text,
  'make' : IDL.Text,
  'trim' : IDL.Text,
  'year' : IDL.Nat,
  'pricePerMile' : IDL.Float64,
  'timestamp' : Time,
  'listingUrl' : IDL.Text,
  'dealerName' : IDL.Text,
  'price' : IDL.Nat,
  'archived' : IDL.Bool,
  'dealScore' : IDL.Text,
  'condition' : IDL.Text,
  'images' : IDL.Vec(ExternalBlob),
});
export const AlertCondition = IDL.Record({
  'field' : IDL.Text,
  'value' : IDL.Text,
  'operator' : IDL.Text,
});
export const CustomAlertFormula = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'conditions' : IDL.Vec(AlertCondition),
});
export const DealExpiryPrediction = IDL.Record({
  'urgency' : IDL.Text,
  'listingId' : IDL.Text,
  'estimatedDaysRemaining' : IDL.Nat,
});
export const DepreciationDataPoint = IDL.Record({
  'avgPrice' : IDL.Float64,
  'monthsFromFirst' : IDL.Nat,
  'listingCount' : IDL.Nat,
});
export const NegotiationScore = IDL.Record({
  'listingId' : IDL.Text,
  'score' : IDL.Nat,
  'factors' : IDL.Vec(IDL.Text),
  'scoreLabel' : IDL.Text,
});
export const RegionalBreakdown = IDL.Record({
  'region' : IDL.Text,
  'avgPrice' : IDL.Float64,
  'sources' : IDL.Vec(IDL.Text),
  'listingCount' : IDL.Nat,
});
export const UpdateListingInput = IDL.Record({
  'region' : IDL.Text,
  'model' : IDL.Text,
  'mileage' : IDL.Nat,
  'source' : IDL.Text,
  'make' : IDL.Text,
  'trim' : IDL.Text,
  'year' : IDL.Nat,
  'listingUrl' : IDL.Text,
  'dealerName' : IDL.Text,
  'price' : IDL.Nat,
  'archived' : IDL.Bool,
  'condition' : IDL.Text,
  'images' : IDL.Vec(ExternalBlob),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkCreateListings' : IDL.Func([IDL.Vec(CreateListingInput)], [], []),
  'createListing' : IDL.Func([CreateListingInput], [], []),
  'deleteCustomAlertFormula' : IDL.Func([IDL.Text], [], []),
  'deletePrivateNote' : IDL.Func([IDL.Text], [], []),
  'evaluateCustomAlertFormulas' : IDL.Func(
      [],
      [IDL.Vec(AlertFormulaMatch)],
      [],
    ),
  'getAllPrivateNotes' : IDL.Func([], [IDL.Vec(PrivateNote)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCrossModelSearch' : IDL.Func(
      [IDL.Float64, IDL.Nat],
      [IDL.Vec(CrossModelResult)],
      ['query'],
    ),
  'getCustomAlertFormulas' : IDL.Func(
      [],
      [IDL.Vec(CustomAlertFormula)],
      ['query'],
    ),
  'getDealExpiryPrediction' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DealExpiryPrediction)],
      ['query'],
    ),
  'getDepreciationCurve' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(DepreciationDataPoint)],
      ['query'],
    ),
  'getNegotiationScore' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(NegotiationScore)],
      ['query'],
    ),
  'getPrivateNote' : IDL.Func([IDL.Text], [IDL.Opt(PrivateNote)], ['query']),
  'getRegionalBreakdown' : IDL.Func(
      [],
      [IDL.Vec(RegionalBreakdown)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCustomAlertFormula' : IDL.Func([CustomAlertFormula], [], []),
  'savePrivateNote' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateListing' : IDL.Func([IDL.Text, UpdateListingInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CreateListingInput = IDL.Record({
    'id' : IDL.Text,
    'region' : IDL.Text,
    'model' : IDL.Text,
    'mileage' : IDL.Nat,
    'source' : IDL.Text,
    'make' : IDL.Text,
    'trim' : IDL.Text,
    'year' : IDL.Nat,
    'listingUrl' : IDL.Text,
    'dealerName' : IDL.Text,
    'price' : IDL.Nat,
    'condition' : IDL.Text,
    'images' : IDL.Vec(ExternalBlob),
  });
  const AlertFormulaMatch = IDL.Record({
    'formulaName' : IDL.Text,
    'matchedListingIds' : IDL.Vec(IDL.Text),
    'formulaId' : IDL.Text,
  });
  const Time = IDL.Int;
  const PrivateNote = IDL.Record({
    'id' : IDL.Text,
    'text' : IDL.Text,
    'lastUpdated' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CrossModelResult = IDL.Record({
    'id' : IDL.Text,
    'region' : IDL.Text,
    'model' : IDL.Text,
    'mileage' : IDL.Nat,
    'source' : IDL.Text,
    'make' : IDL.Text,
    'trim' : IDL.Text,
    'year' : IDL.Nat,
    'pricePerMile' : IDL.Float64,
    'timestamp' : Time,
    'listingUrl' : IDL.Text,
    'dealerName' : IDL.Text,
    'price' : IDL.Nat,
    'archived' : IDL.Bool,
    'dealScore' : IDL.Text,
    'condition' : IDL.Text,
    'images' : IDL.Vec(ExternalBlob),
  });
  const AlertCondition = IDL.Record({
    'field' : IDL.Text,
    'value' : IDL.Text,
    'operator' : IDL.Text,
  });
  const CustomAlertFormula = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'conditions' : IDL.Vec(AlertCondition),
  });
  const DealExpiryPrediction = IDL.Record({
    'urgency' : IDL.Text,
    'listingId' : IDL.Text,
    'estimatedDaysRemaining' : IDL.Nat,
  });
  const DepreciationDataPoint = IDL.Record({
    'avgPrice' : IDL.Float64,
    'monthsFromFirst' : IDL.Nat,
    'listingCount' : IDL.Nat,
  });
  const NegotiationScore = IDL.Record({
    'listingId' : IDL.Text,
    'score' : IDL.Nat,
    'factors' : IDL.Vec(IDL.Text),
    'scoreLabel' : IDL.Text,
  });
  const RegionalBreakdown = IDL.Record({
    'region' : IDL.Text,
    'avgPrice' : IDL.Float64,
    'sources' : IDL.Vec(IDL.Text),
    'listingCount' : IDL.Nat,
  });
  const UpdateListingInput = IDL.Record({
    'region' : IDL.Text,
    'model' : IDL.Text,
    'mileage' : IDL.Nat,
    'source' : IDL.Text,
    'make' : IDL.Text,
    'trim' : IDL.Text,
    'year' : IDL.Nat,
    'listingUrl' : IDL.Text,
    'dealerName' : IDL.Text,
    'price' : IDL.Nat,
    'archived' : IDL.Bool,
    'condition' : IDL.Text,
    'images' : IDL.Vec(ExternalBlob),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkCreateListings' : IDL.Func([IDL.Vec(CreateListingInput)], [], []),
    'createListing' : IDL.Func([CreateListingInput], [], []),
    'deleteCustomAlertFormula' : IDL.Func([IDL.Text], [], []),
    'deletePrivateNote' : IDL.Func([IDL.Text], [], []),
    'evaluateCustomAlertFormulas' : IDL.Func(
        [],
        [IDL.Vec(AlertFormulaMatch)],
        [],
      ),
    'getAllPrivateNotes' : IDL.Func([], [IDL.Vec(PrivateNote)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCrossModelSearch' : IDL.Func(
        [IDL.Float64, IDL.Nat],
        [IDL.Vec(CrossModelResult)],
        ['query'],
      ),
    'getCustomAlertFormulas' : IDL.Func(
        [],
        [IDL.Vec(CustomAlertFormula)],
        ['query'],
      ),
    'getDealExpiryPrediction' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DealExpiryPrediction)],
        ['query'],
      ),
    'getDepreciationCurve' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(DepreciationDataPoint)],
        ['query'],
      ),
    'getNegotiationScore' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(NegotiationScore)],
        ['query'],
      ),
    'getPrivateNote' : IDL.Func([IDL.Text], [IDL.Opt(PrivateNote)], ['query']),
    'getRegionalBreakdown' : IDL.Func(
        [],
        [IDL.Vec(RegionalBreakdown)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCustomAlertFormula' : IDL.Func([CustomAlertFormula], [], []),
    'savePrivateNote' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateListing' : IDL.Func([IDL.Text, UpdateListingInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };