/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateListingInput {
  'id' : string,
  'region' : string,
  'model' : string,
  'mileage' : bigint,
  'source' : string,
  'make' : string,
  'trim' : string,
  'year' : bigint,
  'listingUrl' : string,
  'dealerName' : string,
  'price' : bigint,
  'condition' : string,
  'images' : Array<ExternalBlob>,
}
export interface CrossModelResult {
  'id' : string,
  'region' : string,
  'model' : string,
  'mileage' : bigint,
  'source' : string,
  'make' : string,
  'trim' : string,
  'year' : bigint,
  'pricePerMile' : number,
  'timestamp' : Time,
  'listingUrl' : string,
  'dealerName' : string,
  'price' : bigint,
  'archived' : boolean,
  'dealScore' : string,
  'condition' : string,
  'images' : Array<ExternalBlob>,
}
export interface DepreciationDataPoint {
  'avgPrice' : number,
  'monthsFromFirst' : bigint,
  'listingCount' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface PrivateNote {
  'id' : string,
  'text' : string,
  'lastUpdated' : Time,
}
export interface RegionalBreakdown {
  'region' : string,
  'avgPrice' : number,
  'sources' : Array<string>,
  'listingCount' : bigint,
}
export type Time = bigint;
export interface UpdateListingInput {
  'region' : string,
  'model' : string,
  'mileage' : bigint,
  'source' : string,
  'make' : string,
  'trim' : string,
  'year' : bigint,
  'listingUrl' : string,
  'dealerName' : string,
  'price' : bigint,
  'archived' : boolean,
  'condition' : string,
  'images' : Array<ExternalBlob>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkCreateListings' : ActorMethod<[Array<CreateListingInput>], undefined>,
  'createListing' : ActorMethod<[CreateListingInput], undefined>,
  'deletePrivateNote' : ActorMethod<[string], undefined>,
  'getAllPrivateNotes' : ActorMethod<[], Array<PrivateNote>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCrossModelSearch' : ActorMethod<
    [number, bigint],
    Array<CrossModelResult>
  >,
  'getDepreciationCurve' : ActorMethod<
    [string, string],
    Array<DepreciationDataPoint>
  >,
  'getPrivateNote' : ActorMethod<[string], [] | [PrivateNote]>,
  'getRegionalBreakdown' : ActorMethod<[], Array<RegionalBreakdown>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'savePrivateNote' : ActorMethod<[string, string], undefined>,
  'updateListing' : ActorMethod<[string, UpdateListingInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];